2025-07-24 11:31:34 +0000 - dagster - DEBUG - dlt_data_pipeline_job - 195f8b17-f5d3-4a82-93a2-3219da80e405 - 5367 - LOGS_CAPTURED - Started capturing logs in process (pid: 5367).
2025-07-24 11:31:34 +0000 - dagster - DEBUG - dlt_data_pipeline_job - 195f8b17-f5d3-4a82-93a2-3219da80e405 - 5367 - dlt_pipeline_op - STEP_START - Started execution of step "dlt_pipeline_op".
2025-07-24 11:31:41 +0000 - dagster - ERROR - dlt_data_pipeline_job - 195f8b17-f5d3-4a82-93a2-3219da80e405 - 5367 - dlt_pipeline_op - STEP_FAILURE - Execution of step "dlt_pipeline_op" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "dlt_pipeline_op"::

dlt.pipeline.exceptions.PipelineStepFailed: Pipeline execution failed at `step=extract` when processing package with `load_id=1753356701.0798244` with exception:

<class 'dlt.common.exceptions.MissingDependencyException'>

You must install additional dependencies to run `dlt pyarrow helpers`. If you use pip you may do the following:

pip install "dlt[parquet]"

Install pyarrow to be allow to load arrow tables, panda frames and to use parquet files.

Stack Trace:
  File "/usr/local/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/app/dagster_demo/pipeline.py", line 63, in dlt_pipeline_op
    load_info = pipeline.run(df, table_name="processed_datahe2")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dlt/pipeline/pipeline.py", line 231, in _wrap
    step_info = f(self, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dlt/pipeline/pipeline.py", line 280, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dlt/pipeline/pipeline.py", line 731, in run
    self.extract(
  File "/usr/local/lib/python3.12/site-packages/dlt/pipeline/pipeline.py", line 231, in _wrap
    step_info = f(self, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dlt/pipeline/pipeline.py", line 185, in _wrap
    rv = f(self, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dlt/pipeline/pipeline.py", line 171, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dlt/pipeline/pipeline.py", line 280, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dlt/pipeline/pipeline.py", line 504, in extract
    raise PipelineStepFailed(

The above exception was caused by the following exception:
dlt.common.exceptions.MissingDependencyException: 
You must install additional dependencies to run `dlt pyarrow helpers`. If you use pip you may do the following:

pip install "dlt[parquet]"

Install pyarrow to be allow to load arrow tables, panda frames and to use parquet files.

Stack Trace:
  File "/usr/local/lib/python3.12/site-packages/dlt/pipeline/pipeline.py", line 483, in extract
    self._extract_source(
  File "/usr/local/lib/python3.12/site-packages/dlt/pipeline/pipeline.py", line 1310, in _extract_source
    load_id = extract.extract(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dlt/extract/extract.py", line 456, in extract
    self._extract_single_source(
  File "/usr/local/lib/python3.12/site-packages/dlt/extract/extract.py", line 388, in _extract_single_source
    extractors[item_format].write_items(
  File "/usr/local/lib/python3.12/site-packages/dlt/extract/extractors.py", line 352, in write_items
    for tbl in (
               ^
  File "/usr/local/lib/python3.12/site-packages/dlt/extract/extractors.py", line 355, in <genexpr>
    pandas_to_arrow(item)
  File "/usr/local/lib/python3.12/site-packages/dlt/common/libs/pandas.py", line 13, in pandas_to_arrow
    from dlt.common.libs.pyarrow import pyarrow as pa
  File "/usr/local/lib/python3.12/site-packages/dlt/common/libs/pyarrow.py", line 38, in <module>
    raise MissingDependencyException(

The above exception occurred during handling of the following exception:
ModuleNotFoundError: No module named 'pyarrow'

Stack Trace:
  File "/usr/local/lib/python3.12/site-packages/dlt/common/libs/pyarrow.py", line 31, in <module>
    import pyarrow

